### ISSUE TITLE
Feature request: Make notifications globally configurable

### ISSUE THREAD

**Issue by GF-Huang** [mwakaba2/jupyterlab-notifications#1]
![image](https://user-images.githubusercontent.com/4510984/108455923-1e1a9f00-72aa-11eb-8e97-0b83f92e267a.png)

![image](https://user-images.githubusercontent.com/4510984/108455929-2377e980-72aa-11eb-9bc7-201ca40579cf.png)

**Comment by mwakaba2** [comment]
It's a cell magic, so you need actual code to execute in the cell. 
Can you try this?
```
%%notify -m 'hello'
print('hello')
```

**Comment by GF-Huang** [comment]
Works. But how can I make it works without addition codes?

**Comment by mwakaba2** [comment]
yeah that's not supported at the moment.
Could you tell me more about this feature, and what you expect it to do?

**Comment by GF-Huang** [comment]
Maybe like this:
```
%%notify
```
No need addition codes after `%%notify`.

**Comment by jangenoe** [comment]
Dear Mariko,

Great extension for Jupyterlab.
I feel like this request is indeed more a feature request to enable it for all cells, instead of enabling it each time before a cell needs to be executed.

I suggest to implement this using a settings file in Jupyter lab.

This settings file could look like:
```
{
    // Code completion Extension 
    // mwakaba2/jupyter_notifications:plugin
    // Extension settings.
    // *********************************************

    // Enabled Status
    "enabled": true
    
    // Minimal execution time before a code completion notification is given
    // time given in seconds
    "minimal_time": 120
    
    // Report the time completion has finished
    "report_time": False
    
    // Report cell number when completion has finised
    "report_cell": False
}

**Comment by mwakaba2** [comment]
Thanks for the suggestions! Yeah I can see how enabling notifications for all cells can be useful. 

Instead of using some sort of line magic (command with no additional code in a cell) to enable notifications, @jangenoe I like your suggestion on a global configuration. It allows a user to configure once and not have to re-configure every time in each notebook. 

In addition, once the extension is enabled via settings, the `%notify` cell magic can add a custom message on top of `report_time` and `report_cell` for that particular cell's notification. I'll see if I can implement this sometime this or next week.

**Comment by mwakaba2** [comment]
@jangenoe @GF-Huang Thanks for your patience! 

I scrapped the entire previous ipython magic logic and updated the labextension to make notifications globally configurable
at `Settings --> Advanced Settings Editor --> Notifications`.
In this new release, you'll not be able to set custom messages. I decided not to implement that because there's only enough space to display the cell number and execution time in the browser notification.

Please check out the README for installation instructions.
Thanks again for the feature request! 🙂
