### ISSUE TITLE
Prompts for recordTimings in Markdown cells

### ISSUE THREAD

**Issue by bcaddy** [mwakaba2/jupyterlab-notifications#3]
I keep getting the prompt to set `"recordTiming":true` when executing markdown cells despite the  fact that it is already set to true

**Comment by mwakaba2** [comment]
Hi @bcaddy! Yeah, that's an edge case I didn't consider. 

The extension is giving you that message every time because it expects some code execution metadata but can't find it. I'll fix this and make sure this prompt doesn't show up for markdown and raw cells. I'll release a fix sometime this weekend and let you know when it's ready. 🙂 Thanks for reporting this!

**Comment by mwakaba2** [comment]
@bcaddy Released a new version with the fix (v0.1.4). Please use the following command to upgrade the lab extension.

```bash
$ pip install --upgrade jupyterlab-notifications
```

**Comment by bcaddy** [comment]
That fixed it. Thanks!
