### ISSUE TITLE
Notification not showing up

### ISSUE THREAD

**Issue by gerdm** [mwakaba2/jupyterlab-notifications#32]
Hi,

I'm running JupyterLab version `3.0.14` with `jupyterlab-notifications==0.3.3`, but I can't seem to make the notifications appear. I modified the `minimum_cell_execution_time` to make sure it worked, but it didn't.

To make sure it wasn't my browser, I checkout out the binder link and it worked there.

I tried to rebuild JupyterLab, but it did not work either. Any ideas how to fix this?

Thanks!

**Comment by i-aki-y** [comment]
Hi, @gerdm thank you for your report.
I have confirmed that I can reproduce the problem with the versions you reported.

```
JupyterLab==3.0.14
jupyterlab-notifications==0.3.3
```

I confirmed that the problem was solved by upgrading the jupyterlab version (I checked 3.1.7, 3.1.4, 3.1.0) in my environment.

So if you can, I think the upgrading of jupyterlab is a quick workaround.

**Comment by gerdm** [comment]
Thank you @i-aki-y!
Upgrading to `jupyterlab==3.1.13` fixed the issue.

**Comment by mwakaba2** [comment]
@i-aki-y thanks so much for reproducing the issue and sharing a workaround!

@gerdm  Versions greater than `0.3.0` isn't compatible with `jupyterlab<3.1.0` because the extension relies on a new feature only included in `jupyterlab>=3.1.0`. 
It looks like I forgot to update the readme to highlight this incompatibility, so I'll make sure the docs are updated!
Thanks for reporting this issue!

**Comment by mwakaba2** [comment]
I updated the requirements and added a compatible versions table in the readme. 🙂
https://github.com/mwakaba2/jupyterlab-notifications#compatible-versions-and-requirements-
